# Making sure dependencies are kept up-to-date
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    labels: [ ]
    directory: "/"
    target-branch: "dev"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore: [ci] "
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Berlin"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    labels: [ ]
    directory: "/app"
    target-branch: "dev"
    versioning-strategy: "increase"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "chore: [app] "
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      jest:
        patterns:
        - "jest*"
        - "@types/jest*"
        - "ts-jest*"
      mockfs:
        patterns:
        - "mock-fs*"
        - "@types/mock-fs*"
      typescript:
        patterns:
        - "@typescript-eslint*"
        - "@types/typescript*"
        - 'eslint*'
        - "typescript*"
        - "tsx*"
        - "typedoc*"
      tough-cookie:
        patterns:
        - "tough-cookie*"
        - "@types/tough-cookie*"
      inquirer:
        patterns:
        - "inquirer*"
        - "@types/inquirer*"
      backtrace:
        patterns:
        - "@backtrace*"
    ignore:
      - dependency-name: "@types/node"
        versions: ["22.x.x"] # Ignoring non-LTS version - See https://github.com/nodejs/Release
  
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    labels: [ ]
    directory: "/docker"
    target-branch: "dev"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: [docker] "
    schedule:
      interval: "weekly"
      day: "saturday"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "node"
        versions: ["22.x.x"] # Ignoring non-LTS version - See https://github.com/nodejs/Release

  # Maintain dependencies for pip (docs site)
  - package-ecosystem: "pip"
    labels: [ ]
    directory: "/docs"
    target-branch: "dev"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: [docs] "
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      mkdocs:
        patterns:
        - "mkdocs*"

  # Maintain dependencies for semantic release
  - package-ecosystem: "npm"
    labels: [ ]
    directory: "/.github/actions/helper/prepare-semantic-release"
    target-branch: "dev"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: [semantic-release] "
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      semantic-release:
        patterns:
        - "semantic-release*"
        - "@semantic-release*"
        - "conventional-changelog*"