name: test-api-token-setup
description: Sets up the environment for acquiring an API token for GH runners and connects to a wireguard peer, in order to enable MFA input
inputs:
  app-path:
    description: The path to the app directory
    required: false
    default: app
  wg-endpoint: 
    description: The endpoint of the wireguard server
    required: true
  wg-endpoint-public-key:
    description: The wireguard server's public key
    required: true
  wg-address:
    description: The IP address to assign to the runner
    required: true
  wg-allowed-ips:
    description: The IPs to route through the wireguard tunnel
    required: true
  wg-private-key:
    description: The private key for the runner
    required: true
  wg-preshared-key:
    description: The preshared key for the runner
    required: true
  wg-listen-port:
    description: The port to listen on
    required: true
  wg-dns:
    description: The dns server to use
    required: true
runs:
  using: composite
  steps:
    - id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.app-path }}/node-version
        cache: npm
        cache-dependency-path: ${{ inputs.app-path }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm ci)
    - id: build-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm run build && npm run dist)
    - id: install-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm link)
    - id: setup-wg
      shell: bash
      run: |
        sudo mkdir -p /etc/wireguard
        sudo rm -f /etc/wireguard/wg0.conf
        sudo touch /etc/wireguard/wg0.conf
        echo "[Interface]" | sudo tee -a /etc/wireguard/wg0.conf
        echo "Address = ${{ inputs.wg-address }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "PrivateKey = ${{ inputs.wg-private-key }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "ListenPort = ${{ inputs.wg-listen-port }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "" | sudo tee -a /etc/wireguard/wg0.conf
        echo "[Peer]" | sudo tee -a /etc/wireguard/wg0.conf
        echo "PublicKey = ${{ inputs.wg-endpoint-public-key }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "PresharedKey = ${{ inputs.wg-preshared-key }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "Endpoint = ${{ inputs.wg-endpoint }}" | sudo tee -a /etc/wireguard/wg0.conf
        echo "AllowedIPs = ${{ inputs.wg-allowed-ips }}" | sudo tee -a /etc/wireguard/wg0.conf
    - id: start-wg
      shell: bash
      run: |
        sudo apt install wireguard
        sudo ip link add dev wg0 type wireguard
        sudo ip address add dev wg0 ${{ inputs.wg-address }}/24
        sudo wg setconf wg0 /etc/wireguard/wg0.conf
        sudo ip link set up dev wg0
        sudo wg