name: test-api-token-setup
description: Sets up the environment for acquiring an API token for GH runners and connects to a wireguard peer, in order to enable MFA input
inputs:
  app-path:
    description: The path to the app directory
    required: false
    default: app
  wg-endpoint: 
    description: The endpoint of the wireguard server
    required: true
  wg-endpoint-public-key:
    description: The wireguard server's public key
    required: true
  wg-address:
    description: The IP address to assign to the runner
    required: true
  wg-allowed-ips:
    description: The IPs to route through the wireguard tunnel
    required: true
  wg-private-key:
    description: The private key for the runner
    required: true
  wg-preshared-key:
    description: The preshared key for the runner
    required: true
  wg-listen-port:
    description: The port to listen on
    required: true
runs:
  using: composite
  steps:
    - id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.app-path }}/node-version
        cache: npm
        cache-dependency-path: ${{ inputs.app-path }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm ci)
    - id: build-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm run build)
    - id: install-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm link)
    - id: setup-wg
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install wireguard

        > /etc/wireguard/wg0.conf
        echo "[Interface]" >> /etc/wireguard/wg0.conf
        echo "Address = ${{ inputs.wg-address }}" >> /etc/wireguard/wg0.conf
        echo "PrivateKey = ${{ inputs.wg-private-key }}" >> /etc/wireguard/wg0.conf
        echo "ListenPort = ${{ inputs.wg-listen-port }}" >> /etc/wireguard/wg0.conf
        echo "" >> /etc/wireguard/wg0.conf
        echo "[Peer]" >> /etc/wireguard/wg0.conf
        echo "PublicKey = ${{ inputs.wg-endpoint-public-key }}" >> /etc/wireguard/wg0.conf
        echo "PresharedKey = ${{ inputs.wg-preshared-key }}" >> /etc/wireguard/wg0.conf
        echo "Endpoint = ${{ inputs.wg-endpoint }}" >> /etc/wireguard/wg0.conf
        echo "AllowedIPs = ${{ inputs.wg-allowed-ips }}" >> /etc/wireguard/wg0.conf
    - id: start-wg
      shell: bash
      run: wg-quick up wg0