name: release-docker-setup
description: Sets up the docker release environment
inputs:
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
  docker-path:
    description: The path to the docker directory
    required: false
    default: docker
runs:
  using: composite
  steps:
    - id: prepare-semantic-release
      uses: ./.github/actions/helper/prepare-semantic-release
      with:
        release-config-dir: ${{ github.action_path }}
        release-dir: ${{ inputs.release-dir }}
    - id: get-docker-metadata
      uses: ./.github/actions/helper/docker-metadata
    - id: configure-release
      shell: bash
      run: |
        cat ${{ inputs.release-dir }}/.releaserc.json |\
          jq '.plugins[0][1].dockerContext = "'$(readlink -f {{ inputs.docker-path }}'"' |\
          jq '.plugins[0][1].dockerImage = "${{ steps.get-docker-metadata.outputs.image-repository }}"' |\
          jq '.plugins[0][1].dockerProject= "${{ steps.get-docker-metadata.outputs.image-namespace }}' |\
          sponge ${{ inputs.release-dir }}/.releaserc.json
    - id: prepare-docker-build
      uses: ./.github/actions/build/docker-setup