name: 'Artifacts: Test'
# This workflow will test the requested artifacts
# In order to run E2E and API tests, an Apple ID test user is required. The self-hosted runner is expected to have those set in the `.env` file located in the runner's directory.

on:
  workflow_call:
    inputs:
      methods:
        description: 'An array of test methods that need to be run. Will be read using fromJSON(). Allowed values: ["e2e", "unit-ubuntu", "unit-macos", "api"]'
        required: true
        type: string
    # secrets:
    #   test-apple-id-user: 
    #     description: The username of the Apple ID test user, used during E2E tests
    #     required: false
    #   test-apple-id-pwd:
    #     description: The password of the Apple ID test user, used during E2E tests
    #     required: false
    #   test-trust-token: 
    #     description: The validated trust token of the Apple ID test user
    #     required: false

permissions: {}

jobs:
  unit-ubuntu:
    runs-on: ubuntu-latest
    if: contains(fromJSON(inputs.methods), 'unit-ubuntu')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v4
      - name: setup/test-unit
        uses: ./.github/actions/test/setup
        with:
          prepare-app: true
      - name: action/test-unit
        uses: ./.github/actions/test/unit

  unit-macos:
    runs-on: macos-latest
    if: contains(fromJSON(inputs.methods), 'unit-macos')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v4
      - name: setup/test-unit
        uses: ./.github/actions/test/setup
        with:
          prepare-app: true
      - name: action/test-unit
        uses: ./.github/actions/test/unit

  docker:
    runs-on: [self-hosted, linux, x64, residential] # This workflow needs to be run from a residential IP address and needs to have the necessary secrets set in it's environment
    if: contains(fromJSON(inputs.methods), 'e2e')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v4
      - name: setup/test-docker
        uses: ./.github/actions/test/setup
        with:
          prepare-docker: true
      - name: action/test-docker
        uses: ./.github/actions/test/docker
  
  api:
    runs-on: [self-hosted, linux, x64, residential] # This workflow needs to be run from a residential IP address and needs to have the necessary secrets set in it's environment
    if: contains(fromJSON(inputs.methods), 'api')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v4
      - name: setup/test-api
        uses: ./.github/actions/test/setup
        with:
          prepare-app: true
      - name: action/test-api
        uses: ./.github/actions/test/api