name: 'Artifacts: Test'
# This workflow will test the requested artifacts
# In order to run E2E and API tests, an Apple ID test user is required. The self-hosted runner is expected to have those set in the `.env` file located in the runner's directory.

on:
  workflow_call:
    inputs:
      methods:
        description: 'An array of test methods that need to be run. Will be read using fromJSON(). Allowed values: ["e2e", "unit-ubuntu", "unit-macos", "api"]'
        required: true
        type: string
    secrets:
        gh-token:
          description: The Github Token, in order to comment on pull request
          required: false # Required for PR comments of testing PR

permissions:
  pull-requests: write

jobs:
  unit-ubuntu:
    runs-on: ubuntu-latest
    if: contains(fromJSON(inputs.methods), 'unit-ubuntu')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v5
      - name: setup/test-unit
        uses: ./.github/actions/test/setup
        with:
          prepare: app
      - name: action/test-unit
        uses: ./.github/actions/test/unit
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}


  unit-macos:
    runs-on: macos-latest
    if: contains(fromJSON(inputs.methods), 'unit-macos')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v5
      - name: setup/test-unit
        uses: ./.github/actions/test/setup
        with:
          prepare: app
      - name: action/test-unit
        uses: ./.github/actions/test/unit
        
  unit-docker:
    runs-on: ubuntu-latest
    if: contains(fromJSON(inputs.methods), 'unit-docker')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v5
      - name: setup/test-docker
        uses: ./.github/actions/test/setup
        with:
          prepare: docker
      - name: action/test-docker
        uses: ./.github/actions/test/docker
        with:
          method: unit
          gh-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: [self-hosted, linux, x64, residential] # This workflow needs to be run from a residential IP address and needs to have the necessary secrets set in it's environment
    if: contains(fromJSON(inputs.methods), 'e2e')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v5
      - name: setup/test-docker
        uses: ./.github/actions/test/setup
        with:
          prepare: docker
      - name: action/test-docker
        uses: ./.github/actions/test/docker
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

  
  api:
    runs-on: [self-hosted, linux, x64, residential] # This workflow needs to be run from a residential IP address and needs to have the necessary secrets set in it's environment
    if: contains(fromJSON(inputs.methods), 'api')
    steps:
      - name: setup/checkout
        uses: actions/checkout@v5
      - name: setup/test-api
        uses: ./.github/actions/test/setup
        with:
          prepare: app
      - name: action/test-api
        uses: ./.github/actions/test/api
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
