name: '[event] PR'
run-name: '[event] ${{ github.event.action }} "${{ github.event.pull_request.title }}" targeting {${{ github.event.pull_request.base.ref }}}'
# Upon receiving a PR, this workflow will run all build and test checks required

on:
  pull_request:
    branches:    
      - main
      - beta
      - dev

jobs:
  build:
    name: build
    uses: ./.github/workflows/artifacts_build-release.yml
    with:
      all-artifacts: true
      release: false

  test:
    name: test
    needs: build
    uses: ./.github/workflows/artifacts_test.yml
    permissions: {}
    with:
      methods: ${{github.base_ref == 'main' && '["unit-ubuntu", "unit-macos", "e2e", "api"]' || (github.base_ref == 'beta' && '["unit-ubuntu", "e2e", "api"]' || '["unit-ubuntu"]' ) }} # Only running full suite when targeting beta or main
    # secrets:
    #   test-apple-id-user: ${{ secrets.TEST_APPLE_ID_USER }}
    #   test-apple-id-pwd: ${{ secrets.TEST_APPLE_ID_PWD }}
    #   test-trust-token: ${{ secrets.TEST_TRUST_TOKEN }}