name: '[monitor] iCloud API'
# This workflow continuously runs the API Tests for this project twice a day, in order to check, if the remote API is still compatible with this tool.

on:
  schedule:
    - cron: '20 5,17 * * *'

permissions:
  pull-requests: write

jobs:
  api-test:
    name: api-test
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/artifacts_test.yml
    with:
      methods: '["api"]'